odandecorfinal/odandecorfinal/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views
from mainapp.views import About, Explore_View,Faqs,Explore,Index,ProductDetail
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from django.views.static import serve
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view()),
    path('about/', About.as_view()),
    path('contact/', views.contact, name='contact'),
    path('faqs/', Faqs.as_view()),
    path('explore/', Explore.as_view()),
    # path('cool/', views.Error_404),  # For Debugging 404 page
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('<slug:slug>/', ProductDetail.as_view(), name='product_detail1'),
    path('explore/<slug:slug>/', Explore_View.as_view()),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'mainapp.views.Error_404'

odandecorfinal/mainapp/models.py
from django.db import models
from django.shortcuts import render
from django.urls import reverse
from django.template.defaultfilters import slugify
from datetime import datetime
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

class Category_Section(models.Model):
    category_name = models.CharField(max_length=50, default="")
    starting_price = models.CharField(max_length=50, default="")
    category_description = models.CharField(max_length=300,default="")
    image = models.ImageField(upload_to="img/category")
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.category_name
    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug})
    
class SubCategory(models.Model):
    category = models.ForeignKey(Category_Section,default=None,on_delete=models.CASCADE)
    sub_category = models.CharField(max_length=50, default="")
    def __str__(self):
        return self.sub_category

class Product(models.Model):
    product_name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    product_category = models.ForeignKey(Category_Section, default=None, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory,default=None,on_delete=models.CASCADE)
    description = models.CharField(max_length=300)
    published_date = models.DateField(default=datetime.today)
    image = models.ImageField(upload_to="img", default="",blank=True)
    slug = models.SlugField(max_length=200,unique=True)

    def __str__(self):
        return self.product_name
    
    def get_absolute_url(self):
        return reverse('product_detail1', kwargs={'slug': self.slug})

class KeyPoints(models.Model):
    post = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    key_point = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.post.product_name
class Multi_img(models.Model):
    post = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    supporting_image = models.ImageField(upload_to="img/supporting")

    def __str__(self):
        return self.post.product_name

class Explore_img(models.Model):
    post = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    supporting_image = models.ImageField(upload_to="img/explore")

    def __str__(self):
        return self.post.product_name

class FAQ(models.Model):
    title = models.CharField(max_length=150, default="")

    def __str__(self):
        return self.title
  
class QNA(models.Model):
    post = models.ForeignKey(FAQ, default=None, on_delete=models.CASCADE)
    Question = models.CharField(max_length=500, default="")
    Answer = models.TextField(default="")

    def __str__(self):
        return self.Question

@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.ImageField):
            instance_file_field = getattr(instance,field.name)
            delete_file_if_unused(sender,instance,field,instance_file_field)

@receiver(pre_save)
def delete_files_when_file_changed(sender,instance, **kwargs):
    if not instance.pk:
        return
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.ImageField):
            try:
                instance_in_db = sender.objects.get(pk=instance.pk)
            except sender.DoesNotExist:
                return
            instance_in_db_file_field = getattr(instance_in_db,field.name)
            instance_file_field = getattr(instance,field.name)
            if instance_in_db_file_field.name != instance_file_field.name:
                delete_file_if_unused(sender,instance,field,instance_in_db_file_field)
  
def delete_file_if_unused(model,instance,field,instance_file_field):
    dynamic_field = {}
    dynamic_field[field.name] = instance_file_field.name
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)

odandecorfinal/mainapp/views.py
from django.shortcuts import render
from datetime import date
from django import template
from django.core.mail.message import EmailMultiAlternatives
from .models import FAQ, QNA, Product, Multi_img, Category_Section
from django.conf import settings
from django.views.generic import TemplateView,DetailView,ListView


# Email sending library starts
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
# Email sending library ends

class Index(TemplateView):
    model = Product
    catmodel = Category_Section
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["product"] = self.model.objects.all()
        context["cat"] = self.catmodel.objects.all()
        return context
     
def contact(request):
    if request.method == "POST":
        today = date.today()
        name = request.POST['name']
        emailname = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        # template = render_to_string('thankyou.html', {'name':name})
        context = {'name':name, 'today':today}
        html_content = render_to_string('emailthanks.html', context)
        template = strip_tags(html_content)
        send_mail(
            'Message from' + '  ' + name + '  ' + 'on subject:  ' + subject,
            "His/her email: " + emailname + "\n\n Message starts from here:\n\n" + message,
            emailname,
            ['odandecor@gmail.com'],
            fail_silently = False,
        )
        email = EmailMultiAlternatives(
            'Message from Odan Decor',
            template,
            settings.EMAIL_HOST_USER,
            [emailname],
        )
        email.attach_alternative(html_content,"text/html")
        email.fail_silently = False
        email.send()

        params = {'name':name}
        return render(request,'contact.html',params)
    else:
        return render(request,"contact.html")

class About(TemplateView):
    template_name = "about.html"

class Faqs(TemplateView):
    model = QNA
    template_name = "faqs.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["faq"] = self.model.objects.all()
        return context

class Explore(TemplateView):
    template_name = "explore.html"
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["product"] = self.model.objects.all()
        return context

class ProductDetail(DetailView):
    context_object_name = 'products'
    model = Product
    template_name = "productdetail.html"
    
class Explore_View(DetailView):
    context_object_name = 'explore'
    model = Product
    template_name = "shop.html"

# ### For debugging 404 page
# def Error_404(request):
#     return render(request,"404.html", status=404)
# ###Debugging 404 ends

def Error_404(request,exception):
    return render(request,"404.html", status=404)

odandecorfinal/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% block title %}
<title>About</title>
{% endblock title %}

    <section class="bg-success py-5">
        <div class="container">
            <div class="row align-items-center py-5">
                <div class="col-md-8 text-white">
                    <h1>About Odan Decor</h1>
                    <p>
                        Odan Home Decor never compromise the Customer's Satisfaction. We will always be ready to give our best so that you will get everything what you have paid for.
                    </p>
                </div>
                <div class="col-md-4">
                    <img class ="container about-hero" src="{% static 'img/about-hero.svg' %}" alt="About Hero">
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->

    <!-- Start Section -->
    <section class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Our Services</h1>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-truck fa-lg"></i></div>
                    <h2 class="h5 mt-4 text-center">Delivery Services</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-exchange-alt"></i></div>
                    <h2 class="h5 mt-4 text-center">Shipping & Return</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-percent"></i></div>
                    <h2 class="h5 mt-4 text-center">100% Satisfaction</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-user"></i></div>
                    <h2 class="h5 mt-4 text-center">6AM-8PM(GMT +5:45) Service</h2>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->

    <!-- Start Brands -->
    
    <!--End Brands-->
{% endblock content %}

odandecorfinal/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    
    {% block title %}
    {% comment %} <<<<<<<<<<<<<<<<<<<<<Specific Page Title Comes Here>>>>>>>>>>>>>>>>>>>>>>>>>>>> {% endcomment %}

    {% endblock title %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static 'img/favicon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">

</head>

<body>
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:mail@odandecor.com.np">mail@odandecor.com.np</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:+9779865005559">+977-9855080300</a>
                </div>
                <div>
                    <a class="text-light" href="https://facebook.com/odandecor" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.instagram.com/odandecor" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->


    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1-logo align-self-center" href="/">
                Odan Decor
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/explore/">Explore</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about/">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/faqs/">FAQs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contact/">Contact Us</a>
                        </li>
                    </ul>
                </div>
                {% comment %} 
                
                <div class="navbar align-self-center d-flex">
                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div>
                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                        <i class="fa fa-fw fa-search text-dark mr-2"></i>
                    </a>
                </div> 
                
                {% endcomment %}
            </div>

        </div>
    </nav>
    <!-- Close Header -->

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>


{% block content %}



{% endblock content %}




  <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Odan Decor</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            CG Landmark, 1<sup>st</sup> Floor, Bharatpur, Chitwan
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:+9779865005559">+977-9855080300</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:mail@odandecor.com">mail@odandecor.com.np</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="/explore/kolhapuri-slipper/">Kolhapuri Slipper</a></li>
                        <li><a class="text-decoration-none" href="/explore/jewellery/">Jewellery</a></li>
                        <li><a class="text-decoration-none" href="/explore/wallpaper/">Wallpaper Design</a></li>
                        <li><a class="text-decoration-none" href="/explore/water-fountain/">Water Fountain</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="/">Home</a></li>
                        <li><a class="text-decoration-none" href="/explore/">Explore</a></li>
                        <li><a class="text-decoration-none" href="/about/">About</a></li>
                        <li><a class="text-decoration-none" href="/faqs/">FAQs</a></li>
                        <li><a class="text-decoration-none" href="/contact/">Contact Us</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://m.facebook.com/odandecor/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/odandecor/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                {% comment %} <div class="emailclass col-auto">
                    <label class="sr-only emailfield" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <button class="input-group-text ragasbutton btn-success mx-1 text-light">Subscribe</button>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            &copy; <script type="text/javascript">document.write(new Date().getFullYear());</script> Odan Decor 
                            | Developed by <a href="https://sagarregmi.info.np/" target="_blank">Sagar Regmi</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->

   <!-- Start Script -->
    <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/templatemo.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- End Script -->
</body>

</html>

odandecorfinal/templates/productdetail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% block title %}
<title>{{products.product_name}}</title>
{% endblock title %}

    <!-- Open Content -->
        <section class="bg-light">
        <div class="container pb-5">
            <div class="row">
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="/media/{{products.image}}" alt="Card image cap" id="product-detail">
                    </div>
                {% if products.multi_img_set.all %}
                    <div class="row">
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-dark fas fa-chevron-left"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </div>
                        <!--End Controls-->
                        <!--Start Carousel Wrapper-->
                        <div id="multi-item-example" class="col-10 carousel slide carousel-multi-item" data-bs-ride="carousel">
                            <!--Start Slides-->
                            <div class="carousel-inner product-links-wap" role="listbox">
                                
                                <!--First slide-->
                                
                                <div class="carousel-item active col-4">
                                    <div class="container col-6">
                                        <div class="col-12">
                                            {% for image in products.multi_img_set.all|slice:"0:1" %}
                                            <a href="#">
                                                <img class="card-img img-fluid" src="/media/{{image.supporting_image}}" alt="Product Image 1">
                                            </a>
                                            {% endfor %}
                                        </div>
                                       
                                    </div>
                                </div>  
                                <!--/.First slide-->

                                <!--Second slide-->
                                {% for image in products.multi_img_set.all|slice:"1:"%}
                                <div class="carousel-item col-4">
                                    <div class="container col-6">
                                        <div class="col-12">
                                            <a href="#">
                                                <img class="card-img img-fluid" src="/media/{{image.supporting_image}}" alt="Product Image 4">
                                                
                                            </a>
                                        </div>
                                    </div>
                                </div>        
                                {% endfor %}
                            </div>
                            <!--End Slides-->
                        </div>
                        <!--End Carousel Wrapper-->
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-dark fas fa-chevron-right"></i>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                {% endif %}
                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{products.product_name}}</h1>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h6>Brand:</h6>
                                </li>
                                <li class="list-inline-item">
                                    <p class="text-muted"><strong>{{products.brand}}</strong></p>
                                </li>
                            </ul>

                            <h6>Description:</h6>
                            <p>{{products.description}}</p>

                            <h6>Specification:</h6>
                            <ul class="list-unstyled pb-3">
                            {% for key in products.keypoints_set.all %}
                                <li>
                                {{key.key_point}}
                                </li>
                            {% endfor %}
                            </ul>

                            

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Content -->

    {% endblock content %}

odandecorfinal/templates/shop.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block title %}
<title>{{explore.product_name}}</title>
{% endblock title %}
<!-- Start Content -->
<div class="container py-5">
    <div class="row">

        <div class="col-lg-3">
            <h1 class="h2 pb-4">{{explore.product_name}}</h1>
        </div>

        <!-- Image Text Starts Here -->

        <div class="col-lg-9">
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-inline shop-top-menu pb-3 pt-1">
                        <li class="list-inline-item">
                            <h2>All Products</h2>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="row">

                <div class="col-md-4">
                    <div class="card mb-4 product-wap rounded-0">
                        <div class="card rounded-0">
                            {% for image in explore.explore_img_set.all|slice:"0:1" %}
                            <img class="card-img rounded-0 img-fluid" src="/media/{{image.supporting_image}}">
                            <div
                                class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                <ul class="list-unstyled">
                                    <li><a class="btn btn-success text-white mt-2" href="/{{explore.slug}}/"><i
                                                class="far fa-eye"></i></a></li>
                                </ul>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                {% for image in explore.explore_img_set.all|slice:"1:" %}
                <div class="col-md-4">
                    <div class="card mb-4 product-wap rounded-0">
                        <div class="card rounded-0">

                            <img class="card-img rounded-0 img-fluid" src="/media/{{image.supporting_image}}">
                            <div
                                class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                <ul class="list-unstyled">
                                    <li><a class="btn btn-success text-white mt-2" href="/{{explore.slug}}/"><i
                                                class="far fa-eye"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% comment %} <div div="row">
            <ul class="pagination pagination-lg justify-content-end">
                <li class="page-item disabled">
                    <a class="page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0" href="#"
                        tabindex="-1">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href="#">3</a>
                </li>
            </ul>
        </div> {% endcomment %}
    </div>

</div>
</div>
<!-- End Content -->


{% endblock %}